first attempt to pass homework1
made-mlops-2022/made_mlops_autumn_2022 pull request #1
Opened 2022-11-06 19:50 UTC by katia2145

Проведен анализ данных. 
Применена логистическая регрессия и случайный лес для решения задачи. 
Написаны отдельные функции для обучения, предсказания и разбиения датасета на train и test. Инструкция по запуску этих функции находится в README.md
Данные для тестирования взяты из равномерного распределения, диапазоны значений подобраны на основе EDA.

Задание:

+  Описание к пулреквесту
+  В пулл-реквесте проведена самооценка
+  Выполнено EDA
-  Можете использовать не ноутбук, а скрипт, который сгенерит отчет
+  Написана функция/класс для тренировки модели
+  Написана функция/класс predict
+  Проект имеет модульную структуру
+  Использованы логгеры
+- Написаны тесты на отдельные модули и на прогон обучения и predict
+- Для тестов генерируются синтетические данные, приближенные к реальным
+  Используются датаклассы для сущностей из конфига
-+ Напишите кастомный трансформер и протестируйте его
+  В проекте зафиксированы все зависимости
-  Настроен CI для прогона тестов, линтера на основе github actions
+  Используйте hydra для конфигурирования
-  Mlflow

2022-11-13 09:02 UTC, katia2145 commented
MADE Потапова Екатерина

2022-11-20 21:49 UTC, SVizor42 requested changes
Складывается ощущение в ветке `main` были выполнены какие-то изменения после создания PR, т.к. некорректно отображаются изменения. Поэтому решил вынести все комментарии сюда:
1. Убрать из репозитория `pycache`, логи гидры и прочие посторонние файлы (можно использовать `.gitignore`).
2. Добавить метки `MADE` / `TECHNOPARK` и `hw1` .
3. Много лишних зависимостей. Лучше фиксировать не все зависимости, а только ключевые.
4. В обучающем скрипте должна присутствовать валидация модели, логироваться/сохраняться метрики.
5. Не нужно хардкодить таргет в теле модуля. Лучше вынести его в конфиг или в константы.
6. Указать типы аргументов и возвращаемых значений функций.
7. Трансформер нужно было использовать при тренировке и предсказании. При такой реализации он выглядит как посторонний элемент.
8. Почему в модуле predict используется `argparse` вместо `hydra`? В этом случае можно точно также использовать конфиг.

2022-11-28 12:50 UTC, katia2145 commented
Не поняла, к чему конкретно относится 5 пункт, остальное (кроме, трансформера) исправила.

2022-11-28 21:25 UTC, SVizor42 commented on ml_project/src/train.py
> +    X = X.drop('condition', axis=1)
Пункт 5 - про такой случай

2022-11-28 21:27 UTC, SVizor42 approved these changes
Зачтено. Ветку можно сливать.

**Сумма: 27 баллов**

2022-12-10 13:04 UTC, merged